INC-38/Registration-password
FightersForJustice/inctagram pull request #34
Opened 2023-07-26 08:52 UTC by maskpa100

2023-07-26 15:05 UTC, TURP1 requested changes
**no error before click (first render)**
<img width="503" alt="Знімок екрана 2023-07-26 о 18 03 31" src="https://github.com/FightersForJustice/inctagram/assets/104382770/2f5f77bc-a4e7-4e51-a27e-ba286cb84741">

2023-07-27 20:23 UTC, irinrudko requested changes
очень не нра

2023-07-27 20:23 UTC, irinrudko commented on components/auth/Registration/RegistrationFormContainer.tsx
> +      .catch((error: any) => {
очень не нравятся эти any

2023-07-27 20:23 UTC, irinrudko commented on components/auth/Registration/RegistrationForm.tsx
> +              ...register('password2', { validate: (val) => confirmPassword(val, watch) })
старайся не сокращать слова, это повысит читаемость кода. val – это value, это  validation? что делает watch тоже не совсем понятно

2023-07-27 20:23 UTC, irinrudko commented on components/auth/Login/validate.ts
> +export const confirmPassword = (val: any, watch: any) => {
ну здесь точно надо any поменять на string или что там ещё приходит. так весь смысл TS уходит, если мы везде any ставим

2023-08-01 09:45 UTC, TURP1 commented
нужно зарезолвить конфликты перед тем, как попадет к QA

2023-08-05 07:44 UTC, ilich01 approved these changes

2023-08-05 10:29 UTC, closed without merging