Folder structure refactor
FightersForJustice/inctagram pull request #4
Opened 2023-07-07 16:17 UTC by Viarcinski

Renamed files and folders to "PascalCase" and changed imports

2023-07-07 17:43 UTC, maskpa100 approved these changes

2023-07-07 20:56 UTC, irinrudko commented on assets/api/Auth/AuthApi.ts
Это по каким-то правилам, что надо с большой буквы названия давать? Я знаю только, что компоненты с большой буквы пишем.

2023-07-07 23:40 UTC, FightersForJustice requested changes
change to PaskalCase only components, and folders that consist components.  Types , files like store.ts, validate.ts, authApi & even folder auth should be camelCase. 
Hint: if you change all these files and commit them, the result will be displayed in the pull request

2023-07-08 20:15 UTC, FightersForJustice commented on components/auth/Registration/Type.tsx
type.tsx

2023-07-09 17:15 UTC, TURP1 approved these changes

2023-07-09 17:20 UTC, FightersForJustice approved these changes

2023-07-10 08:01 UTC, irinrudko approved these changes

2023-07-10 10:52 UTC, closed without merging