Sccs for auth 4
FightersForJustice/inctagram pull request #7
Opened 2023-07-08 19:12 UTC by maskpa100

2023-07-09 08:59 UTC, FightersForJustice approved these changes

2023-07-09 11:05 UTC, Viarcinski approved these changes
Looks good to me

2023-07-09 17:17 UTC, TURP1 approved these changes

2023-07-10 07:47 UTC, irinrudko reviewed
let's use 'style' instead of 's'

2023-07-10 07:50 UTC, irinrudko reviewed
let's use 'button' word, not 'btn'. it doesn't save much space, but it's more difficult to read/write the code. I suggest 'button-primary'. etc/

2023-07-10 07:51 UTC, irinrudko commented on styles/_mixin.scss
> +@mixin Large {
what is 'large'? how to use it? where to use it? not clear.
https://sass-lang.com/documentation/at-rules/mixin/

2023-07-10 07:52 UTC, irinrudko commented on styles/_mixin.scss
> +@mixin Primary-btn {
let's use 'button' word, not 'btn'. it doesn't save much space, but it's more difficult to read/write the code. I suggest 'button-primary'. etc

2023-07-10 07:55 UTC, irinrudko requested changes
please rename some of the things

2023-07-10 09:33 UTC, irinrudko requested changes
please rename some of the things

2023-07-11 07:16 UTC, ilich01 approved these changes

2023-07-11 10:15 UTC, merged