fix: form submitting on enter
FightersForJustice/inctagram pull request #85
Opened 2023-08-27 10:58 UTC by Viarcinski

Fix form submitting functionality by refactoring button component. Other minor fixes

2023-08-27 12:36 UTC, TURP1 approved these changes
GJ

2023-08-27 12:43 UTC, irinrudko requested changes
can you please not do any changes to the RegistrationForm component to avoid merging conflicts as I'm also modifying it? 

this task in Jira: https://ictagramteam.atlassian.net/jira/software/projects/INC/boards/3?selectedIssue=INC-79

2023-08-30 10:54 UTC, irinrudko approved these changes

2023-08-30 10:54 UTC, irinrudko approved these changes

2023-09-01 10:08 UTC, merged